services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/fastapi/Dockerfile
        container_name: user_fastapi
        environment:
            PORT: 8000
        ports:
            - '8000:8000'
        restart: "no"

